// Intersection of methods for 128-bit, 256-bit, and 512-bit vectors:
// Code generated by 'go run cmd/simdops/analyze_simd_ops.go > simd/mocks.go'; DO NOT EDIT.

package simd

func VectorSize() int

// Element Type: Int8
//
//	128-bit Type: Int8x16 (Methods: 44)
//	256-bit Type: Int8x32 (Methods: 43)
//	512-bit Type: Int8x64 (Methods: 44)
type Int8s []int8

func LoadInt8Slice([]int8) Int8s
func LoadInt8SlicePart([]int8) Int8s
func (x Int8s) Abs() Int8s
func (x Int8s) Add(y Int8s) Int8s
func (x Int8s) AddSaturated(y Int8s) Int8s
func (x Int8s) And(y Int8s) Int8s
func (x Int8s) AndNot(y Int8s) Int8s
func (x Int8s) AsFloat32s() Float32s
func (x Int8s) AsFloat64s() Float64s
func (x Int8s) AsInt16s() Int16s
func (x Int8s) AsInt32s() Int32s
func (x Int8s) AsInt64s() Int64s
func (x Int8s) AsUint16s() Uint16s
func (x Int8s) AsUint32s() Uint32s
func (x Int8s) AsUint64s() Uint64s
func (x Int8s) AsUint8s() Uint8s
func (x Int8s) Compress(mask Mask8s) Int8s
func (x Int8s) ConcatPermute(y Int8s, indices Uint8s) Int8s
func (x Int8s) Equal(y Int8s) Mask8s
func (x Int8s) Expand(mask Mask8s) Int8s
func (x Int8s) Greater(y Int8s) Mask8s
func (x Int8s) Len() int
func (x Int8s) Masked(mask Mask8s) Int8s
func (x Int8s) Max(y Int8s) Int8s
func (x Int8s) Merge(y Int8s, mask Mask8s) Int8s
func (x Int8s) Min(y Int8s) Int8s
func (x Int8s) Not() Int8s
func (x Int8s) OnesCount() Int8s
func (x Int8s) Or(y Int8s) Int8s
func (x Int8s) Permute(indices Uint8s) Int8s
func (x Int8s) StoreSlice(s []int8)
func (x Int8s) StoreSlicePart(s []int8)
func (x Int8s) String() string
func (x Int8s) Sub(y Int8s) Int8s
func (x Int8s) SubSaturated(y Int8s) Int8s
func (x Int8s) ToMask() (to Mask8s)
func (x Int8s) Xor(y Int8s) Int8s
func (x Int8s) asMask() (to Mask8s)

// Element Type: Int16
//
//	128-bit Type: Int16x8 (Methods: 62)
//	256-bit Type: Int16x16 (Methods: 54)
//	512-bit Type: Int16x32 (Methods: 55)
type Int16s []int16

func LoadInt16Slice([]int16) Int16s
func LoadInt16SlicePart([]int16) Int16s
func (x Int16s) Abs() Int16s
func (x Int16s) Add(y Int16s) Int16s
func (x Int16s) AddSaturated(y Int16s) Int16s
func (x Int16s) And(y Int16s) Int16s
func (x Int16s) AndNot(y Int16s) Int16s
func (x Int16s) AsFloat32s() Float32s
func (x Int16s) AsFloat64s() Float64s
func (x Int16s) AsInt32s() Int32s
func (x Int16s) AsInt64s() Int64s
func (x Int16s) AsInt8s() Int8s
func (x Int16s) AsUint16s() Uint16s
func (x Int16s) AsUint32s() Uint32s
func (x Int16s) AsUint64s() Uint64s
func (x Int16s) AsUint8s() Uint8s
func (x Int16s) Compress(mask Mask16s) Int16s
func (x Int16s) ConcatPermute(y Int16s, indices Uint16s) Int16s
func (x Int16s) DotProductPairs(y Int16s) Int32s
func (x Int16s) Equal(y Int16s) Mask16s
func (x Int16s) Expand(mask Mask16s) Int16s
func (x Int16s) Greater(y Int16s) Mask16s
func (x Int16s) Len() int
func (x Int16s) Masked(mask Mask16s) Int16s
func (x Int16s) Max(y Int16s) Int16s
func (x Int16s) Merge(y Int16s, mask Mask16s) Int16s
func (x Int16s) Min(y Int16s) Int16s
func (x Int16s) Mul(y Int16s) Int16s
func (x Int16s) MulHigh(y Int16s) Int16s
func (x Int16s) Not() Int16s
func (x Int16s) OnesCount() Int16s
func (x Int16s) Or(y Int16s) Int16s
func (x Int16s) Permute(indices Uint16s) Int16s
func (x Int16s) ShiftAllLeft(y uint64) Int16s
func (x Int16s) ShiftAllLeftConcat(shift uint8, y Int16s) Int16s
func (x Int16s) ShiftAllRight(y uint64) Int16s
func (x Int16s) ShiftAllRightConcat(shift uint8, y Int16s) Int16s
func (x Int16s) ShiftLeft(y Int16s) Int16s
func (x Int16s) ShiftLeftConcat(y Int16s, z Int16s) Int16s
func (x Int16s) ShiftRight(y Int16s) Int16s
func (x Int16s) ShiftRightConcat(y Int16s, z Int16s) Int16s
func (x Int16s) StoreSlice(s []int16)
func (x Int16s) StoreSlicePart(s []int16)
func (x Int16s) String() string
func (x Int16s) Sub(y Int16s) Int16s
func (x Int16s) SubSaturated(y Int16s) Int16s
func (x Int16s) ToMask() (to Mask16s)
func (x Int16s) Xor(y Int16s) Int16s
func (x Int16s) asMask() (to Mask16s)

// Element Type: Int32
//
//	128-bit Type: Int32x4 (Methods: 64)
//	256-bit Type: Int32x8 (Methods: 57)
//	512-bit Type: Int32x16 (Methods: 57)
type Int32s []int32

func LoadInt32Slice([]int32) Int32s
func LoadInt32SlicePart([]int32) Int32s
func (x Int32s) Abs() Int32s
func (x Int32s) Add(y Int32s) Int32s
func (x Int32s) And(y Int32s) Int32s
func (x Int32s) AndNot(y Int32s) Int32s
func (x Int32s) AsFloat32s() Float32s
func (x Int32s) AsFloat64s() Float64s
func (x Int32s) AsInt16s() Int16s
func (x Int32s) AsInt64s() Int64s
func (x Int32s) AsInt8s() Int8s
func (x Int32s) AsUint16s() Uint16s
func (x Int32s) AsUint32s() Uint32s
func (x Int32s) AsUint64s() Uint64s
func (x Int32s) AsUint8s() Uint8s
func (x Int32s) Compress(mask Mask32s) Int32s
func (x Int32s) ConcatPermute(y Int32s, indices Uint32s) Int32s
func (x Int32s) ConvertToFloat32() Float32s
func (x Int32s) Equal(y Int32s) Mask32s
func (x Int32s) Expand(mask Mask32s) Int32s
func (x Int32s) Greater(y Int32s) Mask32s
func (x Int32s) LeadingZeros() Int32s
func (x Int32s) Len() int
func (x Int32s) Masked(mask Mask32s) Int32s
func (x Int32s) Max(y Int32s) Int32s
func (x Int32s) Merge(y Int32s, mask Mask32s) Int32s
func (x Int32s) Min(y Int32s) Int32s
func (x Int32s) Mul(y Int32s) Int32s
func (x Int32s) Not() Int32s
func (x Int32s) OnesCount() Int32s
func (x Int32s) Or(y Int32s) Int32s
func (x Int32s) RotateAllLeft(shift uint8) Int32s
func (x Int32s) RotateAllRight(shift uint8) Int32s
func (x Int32s) RotateLeft(y Int32s) Int32s
func (x Int32s) RotateRight(y Int32s) Int32s
func (x Int32s) ShiftAllLeft(y uint64) Int32s
func (x Int32s) ShiftAllLeftConcat(shift uint8, y Int32s) Int32s
func (x Int32s) ShiftAllRight(y uint64) Int32s
func (x Int32s) ShiftAllRightConcat(shift uint8, y Int32s) Int32s
func (x Int32s) ShiftLeft(y Int32s) Int32s
func (x Int32s) ShiftLeftConcat(y Int32s, z Int32s) Int32s
func (x Int32s) ShiftRight(y Int32s) Int32s
func (x Int32s) ShiftRightConcat(y Int32s, z Int32s) Int32s
func (x Int32s) StoreSlice(s []int32)
func (x Int32s) StoreSlicePart(s []int32)
func (x Int32s) String() string
func (x Int32s) Sub(y Int32s) Int32s
func (x Int32s) ToMask() (to Mask32s)
func (x Int32s) Xor(y Int32s) Int32s
func (x Int32s) asMask() (to Mask32s)

// Element Type: Int64
//
//	128-bit Type: Int64x2 (Methods: 57)
//	256-bit Type: Int64x4 (Methods: 55)
//	512-bit Type: Int64x8 (Methods: 57)
type Int64s []int64

func LoadInt64Slice([]int64) Int64s
func LoadInt64SlicePart([]int64) Int64s
func (x Int64s) Abs() Int64s
func (x Int64s) Add(y Int64s) Int64s
func (x Int64s) And(y Int64s) Int64s
func (x Int64s) AndNot(y Int64s) Int64s
func (x Int64s) AsFloat32s() Float32s
func (x Int64s) AsFloat64s() Float64s
func (x Int64s) AsInt16s() Int16s
func (x Int64s) AsInt32s() Int32s
func (x Int64s) AsInt8s() Int8s
func (x Int64s) AsUint16s() Uint16s
func (x Int64s) AsUint32s() Uint32s
func (x Int64s) AsUint64s() Uint64s
func (x Int64s) AsUint8s() Uint8s
func (x Int64s) Compress(mask Mask64s) Int64s
func (x Int64s) ConcatPermute(y Int64s, indices Uint64s) Int64s
func (x Int64s) ConvertToFloat64() Float64s
func (x Int64s) Equal(y Int64s) Mask64s
func (x Int64s) Expand(mask Mask64s) Int64s
func (x Int64s) Greater(y Int64s) Mask64s
func (x Int64s) LeadingZeros() Int64s
func (x Int64s) Len() int
func (x Int64s) Masked(mask Mask64s) Int64s
func (x Int64s) Max(y Int64s) Int64s
func (x Int64s) Merge(y Int64s, mask Mask64s) Int64s
func (x Int64s) Min(y Int64s) Int64s
func (x Int64s) Mul(y Int64s) Int64s
func (x Int64s) Not() Int64s
func (x Int64s) OnesCount() Int64s
func (x Int64s) Or(y Int64s) Int64s
func (x Int64s) RotateAllLeft(shift uint8) Int64s
func (x Int64s) RotateAllRight(shift uint8) Int64s
func (x Int64s) RotateLeft(y Int64s) Int64s
func (x Int64s) RotateRight(y Int64s) Int64s
func (x Int64s) ShiftAllLeft(y uint64) Int64s
func (x Int64s) ShiftAllLeftConcat(shift uint8, y Int64s) Int64s
func (x Int64s) ShiftAllRight(y uint64) Int64s
func (x Int64s) ShiftAllRightConcat(shift uint8, y Int64s) Int64s
func (x Int64s) ShiftLeft(y Int64s) Int64s
func (x Int64s) ShiftLeftConcat(y Int64s, z Int64s) Int64s
func (x Int64s) ShiftRight(y Int64s) Int64s
func (x Int64s) ShiftRightConcat(y Int64s, z Int64s) Int64s
func (x Int64s) StoreSlice(s []int64)
func (x Int64s) StoreSlicePart(s []int64)
func (x Int64s) String() string
func (x Int64s) Sub(y Int64s) Int64s
func (x Int64s) ToMask() (to Mask64s)
func (x Int64s) Xor(y Int64s) Int64s
func (x Int64s) asMask() (to Mask64s)

// Element Type: Uint8
//
//	128-bit Type: Uint8x16 (Methods: 50)
//	256-bit Type: Uint8x32 (Methods: 48)
//	512-bit Type: Uint8x64 (Methods: 51)
type Uint8s []uint8

func LoadUint8Slice([]uint8) Uint8s
func LoadUint8SlicePart([]uint8) Uint8s
func (x Uint8s) AESDecryptLastRound(y Uint32s) Uint8s
func (x Uint8s) AESDecryptOneRound(y Uint32s) Uint8s
func (x Uint8s) AESEncryptLastRound(y Uint32s) Uint8s
func (x Uint8s) AESEncryptOneRound(y Uint32s) Uint8s
func (x Uint8s) Add(y Uint8s) Uint8s
func (x Uint8s) AddSaturated(y Uint8s) Uint8s
func (x Uint8s) And(y Uint8s) Uint8s
func (x Uint8s) AndNot(y Uint8s) Uint8s
func (x Uint8s) AsFloat32s() Float32s
func (x Uint8s) AsFloat64s() Float64s
func (x Uint8s) AsInt16s() Int16s
func (x Uint8s) AsInt32s() Int32s
func (x Uint8s) AsInt64s() Int64s
func (x Uint8s) AsInt8s() Int8s
func (x Uint8s) AsUint16s() Uint16s
func (x Uint8s) AsUint32s() Uint32s
func (x Uint8s) AsUint64s() Uint64s
func (x Uint8s) Average(y Uint8s) Uint8s
func (x Uint8s) Compress(mask Mask8s) Uint8s
func (x Uint8s) ConcatPermute(y Uint8s, indices Uint8s) Uint8s
func (x Uint8s) DotProductPairsSaturated(y Int8s) Int16s
func (x Uint8s) Equal(y Uint8s) Mask8s
func (x Uint8s) Expand(mask Mask8s) Uint8s
func (x Uint8s) GaloisFieldAffineTransform(y Uint64s, b uint8) Uint8s
func (x Uint8s) GaloisFieldAffineTransformInverse(y Uint64s, b uint8) Uint8s
func (x Uint8s) GaloisFieldMul(y Uint8s) Uint8s
func (x Uint8s) Len() int
func (x Uint8s) Masked(mask Mask8s) Uint8s
func (x Uint8s) Max(y Uint8s) Uint8s
func (x Uint8s) Merge(y Uint8s, mask Mask8s) Uint8s
func (x Uint8s) Min(y Uint8s) Uint8s
func (x Uint8s) Not() Uint8s
func (x Uint8s) OnesCount() Uint8s
func (x Uint8s) Or(y Uint8s) Uint8s
func (x Uint8s) Permute(indices Uint8s) Uint8s
func (x Uint8s) StoreSlice(s []uint8)
func (x Uint8s) StoreSlicePart(s []uint8)
func (x Uint8s) String() string
func (x Uint8s) Sub(y Uint8s) Uint8s
func (x Uint8s) SubSaturated(y Uint8s) Uint8s
func (x Uint8s) SumAbsDiff(y Uint8s) Uint16s
func (x Uint8s) Xor(y Uint8s) Uint8s

// Element Type: Uint16
//
//	128-bit Type: Uint16x8 (Methods: 55)
//	256-bit Type: Uint16x16 (Methods: 49)
//	512-bit Type: Uint16x32 (Methods: 52)
type Uint16s []uint16

func LoadUint16Slice([]uint16) Uint16s
func LoadUint16SlicePart([]uint16) Uint16s
func (x Uint16s) Add(y Uint16s) Uint16s
func (x Uint16s) AddSaturated(y Uint16s) Uint16s
func (x Uint16s) And(y Uint16s) Uint16s
func (x Uint16s) AndNot(y Uint16s) Uint16s
func (x Uint16s) AsFloat32s() Float32s
func (x Uint16s) AsFloat64s() Float64s
func (x Uint16s) AsInt16s() Int16s
func (x Uint16s) AsInt32s() Int32s
func (x Uint16s) AsInt64s() Int64s
func (x Uint16s) AsInt8s() Int8s
func (x Uint16s) AsUint32s() Uint32s
func (x Uint16s) AsUint64s() Uint64s
func (x Uint16s) AsUint8s() Uint8s
func (x Uint16s) Average(y Uint16s) Uint16s
func (x Uint16s) Compress(mask Mask16s) Uint16s
func (x Uint16s) ConcatPermute(y Uint16s, indices Uint16s) Uint16s
func (x Uint16s) Equal(y Uint16s) Mask16s
func (x Uint16s) Expand(mask Mask16s) Uint16s
func (x Uint16s) Len() int
func (x Uint16s) Masked(mask Mask16s) Uint16s
func (x Uint16s) Max(y Uint16s) Uint16s
func (x Uint16s) Merge(y Uint16s, mask Mask16s) Uint16s
func (x Uint16s) Min(y Uint16s) Uint16s
func (x Uint16s) Mul(y Uint16s) Uint16s
func (x Uint16s) MulHigh(y Uint16s) Uint16s
func (x Uint16s) Not() Uint16s
func (x Uint16s) OnesCount() Uint16s
func (x Uint16s) Or(y Uint16s) Uint16s
func (x Uint16s) Permute(indices Uint16s) Uint16s
func (x Uint16s) ShiftAllLeft(y uint64) Uint16s
func (x Uint16s) ShiftAllLeftConcat(shift uint8, y Uint16s) Uint16s
func (x Uint16s) ShiftAllRight(y uint64) Uint16s
func (x Uint16s) ShiftAllRightConcat(shift uint8, y Uint16s) Uint16s
func (x Uint16s) ShiftLeft(y Uint16s) Uint16s
func (x Uint16s) ShiftLeftConcat(y Uint16s, z Uint16s) Uint16s
func (x Uint16s) ShiftRight(y Uint16s) Uint16s
func (x Uint16s) ShiftRightConcat(y Uint16s, z Uint16s) Uint16s
func (x Uint16s) StoreSlice(s []uint16)
func (x Uint16s) StoreSlicePart(s []uint16)
func (x Uint16s) String() string
func (x Uint16s) Sub(y Uint16s) Uint16s
func (x Uint16s) SubSaturated(y Uint16s) Uint16s
func (x Uint16s) Xor(y Uint16s) Uint16s

// Element Type: Uint32
//
//	128-bit Type: Uint32x4 (Methods: 64)
//	256-bit Type: Uint32x8 (Methods: 52)
//	512-bit Type: Uint32x16 (Methods: 54)
type Uint32s []uint32

func LoadUint32Slice([]uint32) Uint32s
func LoadUint32SlicePart([]uint32) Uint32s
func (x Uint32s) Add(y Uint32s) Uint32s
func (x Uint32s) And(y Uint32s) Uint32s
func (x Uint32s) AndNot(y Uint32s) Uint32s
func (x Uint32s) AsFloat32s() Float32s
func (x Uint32s) AsFloat64s() Float64s
func (x Uint32s) AsInt16s() Int16s
func (x Uint32s) AsInt32s() Int32s
func (x Uint32s) AsInt64s() Int64s
func (x Uint32s) AsInt8s() Int8s
func (x Uint32s) AsUint16s() Uint16s
func (x Uint32s) AsUint64s() Uint64s
func (x Uint32s) AsUint8s() Uint8s
func (x Uint32s) Compress(mask Mask32s) Uint32s
func (x Uint32s) ConcatPermute(y Uint32s, indices Uint32s) Uint32s
func (x Uint32s) ConvertToFloat32() Float32s
func (x Uint32s) Equal(y Uint32s) Mask32s
func (x Uint32s) Expand(mask Mask32s) Uint32s
func (x Uint32s) LeadingZeros() Uint32s
func (x Uint32s) Len() int
func (x Uint32s) Masked(mask Mask32s) Uint32s
func (x Uint32s) Max(y Uint32s) Uint32s
func (x Uint32s) Merge(y Uint32s, mask Mask32s) Uint32s
func (x Uint32s) Min(y Uint32s) Uint32s
func (x Uint32s) Mul(y Uint32s) Uint32s
func (x Uint32s) Not() Uint32s
func (x Uint32s) OnesCount() Uint32s
func (x Uint32s) Or(y Uint32s) Uint32s
func (x Uint32s) RotateAllLeft(shift uint8) Uint32s
func (x Uint32s) RotateAllRight(shift uint8) Uint32s
func (x Uint32s) RotateLeft(y Uint32s) Uint32s
func (x Uint32s) RotateRight(y Uint32s) Uint32s
func (x Uint32s) ShiftAllLeft(y uint64) Uint32s
func (x Uint32s) ShiftAllLeftConcat(shift uint8, y Uint32s) Uint32s
func (x Uint32s) ShiftAllRight(y uint64) Uint32s
func (x Uint32s) ShiftAllRightConcat(shift uint8, y Uint32s) Uint32s
func (x Uint32s) ShiftLeft(y Uint32s) Uint32s
func (x Uint32s) ShiftLeftConcat(y Uint32s, z Uint32s) Uint32s
func (x Uint32s) ShiftRight(y Uint32s) Uint32s
func (x Uint32s) ShiftRightConcat(y Uint32s, z Uint32s) Uint32s
func (x Uint32s) StoreSlice(s []uint32)
func (x Uint32s) StoreSlicePart(s []uint32)
func (x Uint32s) String() string
func (x Uint32s) Sub(y Uint32s) Uint32s
func (x Uint32s) Xor(y Uint32s) Uint32s

// Element Type: Uint64
//
//	128-bit Type: Uint64x2 (Methods: 54)
//	256-bit Type: Uint64x4 (Methods: 51)
//	512-bit Type: Uint64x8 (Methods: 54)
type Uint64s []uint64

func LoadUint64Slice([]uint64) Uint64s
func LoadUint64SlicePart([]uint64) Uint64s
func (x Uint64s) Add(y Uint64s) Uint64s
func (x Uint64s) And(y Uint64s) Uint64s
func (x Uint64s) AndNot(y Uint64s) Uint64s
func (x Uint64s) AsFloat32s() Float32s
func (x Uint64s) AsFloat64s() Float64s
func (x Uint64s) AsInt16s() Int16s
func (x Uint64s) AsInt32s() Int32s
func (x Uint64s) AsInt64s() Int64s
func (x Uint64s) AsInt8s() Int8s
func (x Uint64s) AsUint16s() Uint16s
func (x Uint64s) AsUint32s() Uint32s
func (x Uint64s) AsUint8s() Uint8s
func (x Uint64s) Compress(mask Mask64s) Uint64s
func (x Uint64s) ConcatPermute(y Uint64s, indices Uint64s) Uint64s
func (x Uint64s) ConvertToFloat64() Float64s
func (x Uint64s) Equal(y Uint64s) Mask64s
func (x Uint64s) Expand(mask Mask64s) Uint64s
func (x Uint64s) LeadingZeros() Uint64s
func (x Uint64s) Len() int
func (x Uint64s) Masked(mask Mask64s) Uint64s
func (x Uint64s) Max(y Uint64s) Uint64s
func (x Uint64s) Merge(y Uint64s, mask Mask64s) Uint64s
func (x Uint64s) Min(y Uint64s) Uint64s
func (x Uint64s) Mul(y Uint64s) Uint64s
func (x Uint64s) Not() Uint64s
func (x Uint64s) OnesCount() Uint64s
func (x Uint64s) Or(y Uint64s) Uint64s
func (x Uint64s) RotateAllLeft(shift uint8) Uint64s
func (x Uint64s) RotateAllRight(shift uint8) Uint64s
func (x Uint64s) RotateLeft(y Uint64s) Uint64s
func (x Uint64s) RotateRight(y Uint64s) Uint64s
func (x Uint64s) ShiftAllLeft(y uint64) Uint64s
func (x Uint64s) ShiftAllLeftConcat(shift uint8, y Uint64s) Uint64s
func (x Uint64s) ShiftAllRight(y uint64) Uint64s
func (x Uint64s) ShiftAllRightConcat(shift uint8, y Uint64s) Uint64s
func (x Uint64s) ShiftLeft(y Uint64s) Uint64s
func (x Uint64s) ShiftLeftConcat(y Uint64s, z Uint64s) Uint64s
func (x Uint64s) ShiftRight(y Uint64s) Uint64s
func (x Uint64s) ShiftRightConcat(y Uint64s, z Uint64s) Uint64s
func (x Uint64s) StoreSlice(s []uint64)
func (x Uint64s) StoreSlicePart(s []uint64)
func (x Uint64s) String() string
func (x Uint64s) Sub(y Uint64s) Uint64s
func (x Uint64s) Xor(y Uint64s) Uint64s

// Element Type: Float32
//
//	128-bit Type: Float32x4 (Methods: 61)
//	256-bit Type: Float32x8 (Methods: 59)
//	512-bit Type: Float32x16 (Methods: 53)
type Float32s []float32

func LoadFloat32Slice([]float32) Float32s
func LoadFloat32SlicePart([]float32) Float32s
func (x Float32s) Add(y Float32s) Float32s
func (x Float32s) AsFloat64s() Float64s
func (x Float32s) AsInt16s() Int16s
func (x Float32s) AsInt32s() Int32s
func (x Float32s) AsInt64s() Int64s
func (x Float32s) AsInt8s() Int8s
func (x Float32s) AsUint16s() Uint16s
func (x Float32s) AsUint32s() Uint32s
func (x Float32s) AsUint64s() Uint64s
func (x Float32s) AsUint8s() Uint8s
func (x Float32s) CeilScaled(prec uint8) Float32s
func (x Float32s) CeilScaledResidue(prec uint8) Float32s
func (x Float32s) Compress(mask Mask32s) Float32s
func (x Float32s) ConcatPermute(y Float32s, indices Uint32s) Float32s
func (x Float32s) ConvertToInt32() Int32s
func (x Float32s) ConvertToUint32() Uint32s
func (x Float32s) Div(y Float32s) Float32s
func (x Float32s) Equal(y Float32s) Mask32s
func (x Float32s) Expand(mask Mask32s) Float32s
func (x Float32s) FloorScaled(prec uint8) Float32s
func (x Float32s) FloorScaledResidue(prec uint8) Float32s
func (x Float32s) Greater(y Float32s) Mask32s
func (x Float32s) GreaterEqual(y Float32s) Mask32s
func (x Float32s) IsNaN() Mask32s
func (x Float32s) Len() int
func (x Float32s) Less(y Float32s) Mask32s
func (x Float32s) LessEqual(y Float32s) Mask32s
func (x Float32s) Masked(mask Mask32s) Float32s
func (x Float32s) Max(y Float32s) Float32s
func (x Float32s) Merge(y Float32s, mask Mask32s) Float32s
func (x Float32s) Min(y Float32s) Float32s
func (x Float32s) Mul(y Float32s) Float32s
func (x Float32s) MulAdd(y Float32s, z Float32s) Float32s
func (x Float32s) MulAddSub(y Float32s, z Float32s) Float32s
func (x Float32s) MulSubAdd(y Float32s, z Float32s) Float32s
func (x Float32s) NotEqual(y Float32s) Mask32s
func (x Float32s) Reciprocal() Float32s
func (x Float32s) ReciprocalSqrt() Float32s
func (x Float32s) RoundToEvenScaled(prec uint8) Float32s
func (x Float32s) RoundToEvenScaledResidue(prec uint8) Float32s
func (x Float32s) Scale(y Float32s) Float32s
func (x Float32s) Sqrt() Float32s
func (x Float32s) StoreSlice(s []float32)
func (x Float32s) StoreSlicePart(s []float32)
func (x Float32s) String() string
func (x Float32s) Sub(y Float32s) Float32s
func (x Float32s) TruncScaled(prec uint8) Float32s
func (x Float32s) TruncScaledResidue(prec uint8) Float32s

// Element Type: Float64
//
//	128-bit Type: Float64x2 (Methods: 61)
//	256-bit Type: Float64x4 (Methods: 59)
//	512-bit Type: Float64x8 (Methods: 53)
type Float64s []float64

func LoadFloat64Slice([]float64) Float64s
func LoadFloat64SlicePart([]float64) Float64s
func (x Float64s) Add(y Float64s) Float64s
func (x Float64s) AsFloat32s() Float32s
func (x Float64s) AsInt16s() Int16s
func (x Float64s) AsInt32s() Int32s
func (x Float64s) AsInt64s() Int64s
func (x Float64s) AsInt8s() Int8s
func (x Float64s) AsUint16s() Uint16s
func (x Float64s) AsUint32s() Uint32s
func (x Float64s) AsUint64s() Uint64s
func (x Float64s) AsUint8s() Uint8s
func (x Float64s) CeilScaled(prec uint8) Float64s
func (x Float64s) CeilScaledResidue(prec uint8) Float64s
func (x Float64s) Compress(mask Mask64s) Float64s
func (x Float64s) ConcatPermute(y Float64s, indices Uint64s) Float64s
func (x Float64s) ConvertToInt64() Int64s
func (x Float64s) ConvertToUint64() Uint64s
func (x Float64s) Div(y Float64s) Float64s
func (x Float64s) Equal(y Float64s) Mask64s
func (x Float64s) Expand(mask Mask64s) Float64s
func (x Float64s) FloorScaled(prec uint8) Float64s
func (x Float64s) FloorScaledResidue(prec uint8) Float64s
func (x Float64s) Greater(y Float64s) Mask64s
func (x Float64s) GreaterEqual(y Float64s) Mask64s
func (x Float64s) IsNaN() Mask64s
func (x Float64s) Len() int
func (x Float64s) Less(y Float64s) Mask64s
func (x Float64s) LessEqual(y Float64s) Mask64s
func (x Float64s) Masked(mask Mask64s) Float64s
func (x Float64s) Max(y Float64s) Float64s
func (x Float64s) Merge(y Float64s, mask Mask64s) Float64s
func (x Float64s) Min(y Float64s) Float64s
func (x Float64s) Mul(y Float64s) Float64s
func (x Float64s) MulAdd(y Float64s, z Float64s) Float64s
func (x Float64s) MulAddSub(y Float64s, z Float64s) Float64s
func (x Float64s) MulSubAdd(y Float64s, z Float64s) Float64s
func (x Float64s) NotEqual(y Float64s) Mask64s
func (x Float64s) Reciprocal() Float64s
func (x Float64s) ReciprocalSqrt() Float64s
func (x Float64s) RoundToEvenScaled(prec uint8) Float64s
func (x Float64s) RoundToEvenScaledResidue(prec uint8) Float64s
func (x Float64s) Scale(y Float64s) Float64s
func (x Float64s) Sqrt() Float64s
func (x Float64s) StoreSlice(s []float64)
func (x Float64s) StoreSlicePart(s []float64)
func (x Float64s) String() string
func (x Float64s) Sub(y Float64s) Float64s
func (x Float64s) TruncScaled(prec uint8) Float64s
func (x Float64s) TruncScaledResidue(prec uint8) Float64s

// Element Type: Mask8
//
//	128-bit Type: Mask8x16 (Methods: 3)
//	256-bit Type: Mask8x32 (Methods: 3)
//	512-bit Type: Mask8x64 (Methods: 3)
type Mask8s []int8

func LoadMask8Slice([]int8) Mask8s
func LoadMask8SlicePart([]int8) Mask8s
func (x Mask8s) And(y Mask8s) Mask8s
func (x Mask8s) Or(y Mask8s) Mask8s
func (x Mask8s) ToInt8s() (to Int8s)

// Element Type: Mask16
//
//	128-bit Type: Mask16x8 (Methods: 3)
//	256-bit Type: Mask16x16 (Methods: 3)
//	512-bit Type: Mask16x32 (Methods: 3)
type Mask16s []int16

func LoadMask16Slice([]int16) Mask16s
func LoadMask16SlicePart([]int16) Mask16s
func (x Mask16s) And(y Mask16s) Mask16s
func (x Mask16s) Or(y Mask16s) Mask16s
func (x Mask16s) ToInt16s() (to Int16s)

// Element Type: Mask32
//
//	128-bit Type: Mask32x4 (Methods: 3)
//	256-bit Type: Mask32x8 (Methods: 3)
//	512-bit Type: Mask32x16 (Methods: 3)
type Mask32s []int32

func LoadMask32Slice([]int32) Mask32s
func LoadMask32SlicePart([]int32) Mask32s
func (x Mask32s) And(y Mask32s) Mask32s
func (x Mask32s) Or(y Mask32s) Mask32s
func (x Mask32s) ToInt32s() (to Int32s)

// Element Type: Mask64
//
//	128-bit Type: Mask64x2 (Methods: 3)
//	256-bit Type: Mask64x4 (Methods: 3)
//	512-bit Type: Mask64x8 (Methods: 3)
type Mask64s []int64

func LoadMask64Slice([]int64) Mask64s
func LoadMask64SlicePart([]int64) Mask64s
func (x Mask64s) And(y Mask64s) Mask64s
func (x Mask64s) Or(y Mask64s) Mask64s
func (x Mask64s) ToInt64s() (to Int64s)
